// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a destination cannot be written to, or that it can.
 *
 * The mock-up shows only AVAILABLE and UNAVAILABLE. That is not enough: a
 * drive that is unplugged and a drive that is plugged in but *refused* need
 * different words, because only one of them is fixed by plugging it in.
 */
export type Availability = "available" | "disconnected" | "refused" | "identity_mismatch" | "unverifiable";
