// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a filesystem distinguishes `Photo.RAW` from `photo.raw`.
 *
 * NTFS is insensitive, ext4 is sensitive, and exFAT differs by host. The diff
 * logic must not assume either, so it compares through this rather than
 * through `Path`'s own `==`.
 */
export type CaseSensitivity = "sensitive" | "insensitive";
