// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopyFailure } from "./CopyFailure";

/**
 * What a copy actually did.
 */
export type CopyReport = { 
/**
 * Files written and renamed into place.
 */
files_copied: number, 
/**
 * Bytes written.
 */
bytes_copied: number, 
/**
 * Directories created.
 */
directories_created: number, 
/**
 * Files that could not be read or written. Each one means the run is
 * `Partial`, never `Ok`.
 */
failures: Array<CopyFailure>, 
/**
 * Whether the run stopped because it was asked to.
 */
cancelled: boolean, };
