// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file that could not be copied.
 */
export type CopyFailure = { 
/**
 * Path relative to the source root.
 */
relative: string, 
/**
 * What went wrong, in the words the OS used.
 */
message: string, };
