// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Errors surfaced by the core to its callers.
 */
export type CoreError = { "kind": "not_found", "message": string } | { "kind": "invalid", "message": string } | { "kind": "refused", "message": string } | { "kind": "volume_unavailable", "message": string } | { "kind": "io", "message": string } | { "kind": "store", "message": string };
