// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where Shelv keeps what it remembers.
 *
 * Both paths are derived from the user's local application data folder, not
 * from where the executable sits — which is why replacing the binary keeps
 * every rule, drive and nickname. That is the intent: an update must not
 * lose someone's backup configuration.
 */
export type DataLocations = { 
/**
 * The `SQLite` database: rules, destinations, tags, drives and history.
 */
database: string, 
/**
 * The webview's profile directory, which holds the window's own
 * preferences. Filled in by the shell, which is what decides where the
 * webview keeps it.
 */
webview_profile: string, };
