// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A date on somebody's calendar, with no time and no zone.
 *
 * Two of these can be compared, and that comparison is the whole of what
 * the scheduler needs: not how far apart two instants are, but whether
 * they fall on different days.
 */
export type Date = { 
/**
 * Proleptic Gregorian year.
 */
year: number, 
/**
 * 1–12.
 */
month: number, 
/**
 * 1–31.
 */
day: number, };
