// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an unattended run was about to remove, when that looked wrong.
 */
export type DeletionRefusal = { 
/**
 * Files the plan would have removed from the destination.
 */
deletions: number, 
/**
 * Files that were there.
 */
destination_files: number, };
