// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Destination } from "./Destination";
import type { VolumeStatus } from "./VolumeStatus";

/**
 * A destination with its current reachability.
 */
export type DestinationStatus = { 
/**
 * The destination itself.
 */
destination: Destination, 
/**
 * The volume it lives on, and whether that volume is usable.
 */
status: VolumeStatus, };
