// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DestinationId } from "./DestinationId";
import type { RuleId } from "./RuleId";
import type { VolumePath } from "./VolumePath";

/**
 * A backup destination belonging to a rule.
 */
export type Destination = { 
/**
 * Row id.
 */
id: DestinationId, 
/**
 * The rule this destination belongs to.
 */
rule: RuleId, 
/**
 * Where the backup is written.
 */
path: VolumePath, 
/**
 * Display order within the rule.
 */
sort_order: number, };
