// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DestinationId } from "./DestinationId";
import type { PlanOutcome } from "./PlanOutcome";

/**
 * One destination's share of a rule's plan.
 */
export type DestinationPlan = { 
/**
 * Which destination this is.
 */
destination: DestinationId, 
/**
 * What would happen there.
 */
outcome: PlanOutcome, };
