// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of device backs a volume.
 *
 * Shelv accepts only [`Fixed`](DriveType::Fixed) and
 * [`Removable`](DriveType::Removable); the rest are refused so that a rule
 * cannot be pointed at a network share (`docs/PLAN.md` §4.2).
 */
export type DriveType = "fixed" | "removable" | "network" | "optical" | "ram_disk" | "unknown";
