// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VolumeStatus } from "./VolumeStatus";

/**
 * One row of the drives table.
 */
export type DriveRow = { 
/**
 * The drive and whether it can be written to right now.
 */
status: VolumeStatus, 
/**
 * How many rules use it, as a source or as a destination.
 *
 * Shown so the user can see what forgetting a drive would break before
 * they try, rather than being told only when it is refused.
 */
rule_count: number, };
