// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date";
import type { NeverAutomatic } from "./NeverAutomatic";

/**
 * Whether a rule wants to run, and if not, what would change that.
 */
export type Due = { "kind": "now" } | { "kind": "on", 
/**
 * The first day the rule will be due again.
 */
date: Date, } | { "kind": "never", 
/**
 * Why, so the table can say which.
 */
reason: NeverAutomatic, };
