// Generated by scripts/gen-types.sh. Do not edit.
//
// These mirror the Rust types in shelv-core that cross the IPC
// boundary. CI fails if they drift from the Rust.

export type { Availability } from "./Availability";
export type { CaseSensitivity } from "./CaseSensitivity";
export type { CoreError } from "./CoreError";
export type { Destination } from "./Destination";
export type { DestinationId } from "./DestinationId";
export type { DestinationStatus } from "./DestinationStatus";
export type { DriveRow } from "./DriveRow";
export type { DriveType } from "./DriveType";
export type { EventLevel } from "./EventLevel";
export type { Layout } from "./Layout";
export type { Packaging } from "./Packaging";
export type { PickedFolder } from "./PickedFolder";
export type { PinState } from "./PinState";
export type { PlaceholderPolicy } from "./PlaceholderPolicy";
export type { PlaceholderState } from "./PlaceholderState";
export type { Retention } from "./Retention";
export type { Rule } from "./Rule";
export type { RuleId } from "./RuleId";
export type { RuleProblem } from "./RuleProblem";
export type { RuleRow } from "./RuleRow";
export type { RuleSpec } from "./RuleSpec";
export type { Run } from "./Run";
export type { RunEvent } from "./RunEvent";
export type { RunId } from "./RunId";
export type { RunResult } from "./RunResult";
export type { RunStats } from "./RunStats";
export type { RunTrigger } from "./RunTrigger";
export type { Schedule } from "./Schedule";
export type { SpaceInfo } from "./SpaceInfo";
export type { StoredVolume } from "./StoredVolume";
export type { Tag } from "./Tag";
export type { TagId } from "./TagId";
export type { VolumeId } from "./VolumeId";
export type { VolumeIdentity } from "./VolumeIdentity";
export type { VolumeIdentityKind } from "./VolumeIdentityKind";
export type { VolumeInfo } from "./VolumeInfo";
export type { VolumePath } from "./VolumePath";
export type { VolumeStatus } from "./VolumeStatus";
