// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a backup is laid out at the destination.
 */
export type Layout = "mirror" | "snapshot";
