// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a rule will never start by itself.
 */
export type NeverAutomatic = "disabled" | "manual" | "unsupported_schedule";
