// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether files are copied as-is or packed into an archive.
 *
 * Every option is lossless. `ZipStore` packs without compressing, which is
 * the right choice for RAW and JPEG: they are already entropy-coded, so
 * deflate costs full CPU for a few percent (`docs/PLAN.md` §1.1b).
 */
export type Packaging = "files" | "zip_store" | "zip_deflate";
