// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VolumePath } from "./VolumePath";

/**
 * A folder the user picked, resolved against its volume.
 */
export type PickedFolder = { 
/**
 * Where this is, in the coordinates a rule stores: a volume and a path
 * relative to its mount point.
 */
path: VolumePath, 
/**
 * The volume's label, for display.
 */
volume_label: string | null, 
/**
 * The volume serial, where the platform reports one.
 *
 * Display only, and only as a fallback: it is what lets two unlabelled
 * drives that have taken turns in the same port be told apart in the
 * editor, which would otherwise call both of them `E:\`.
 */
volume_serial: string | null, 
/**
 * Where the volume is mounted right now.
 *
 * **Display only.** It is returned so the editor can show the user the
 * full path they just chose; nothing accepts it back as input.
 */
mount_point: string, 
/**
 * The full path as the user would recognise it, for a tooltip.
 */
display_path: string, };
