// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the user has asked for a cloud file to be kept on local disk.
 */
export type PinState = "pinned" | "unpinned" | "unspecified";
