// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a file's content is actually present on local disk.
 */
export type PlaceholderState = "full" | "dehydrated" | "partially_hydrated" | "hydrated";
