// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to do about cloud files whose content is not on local disk.
 */
export type PlaceholderPolicy = "hydrate" | "hydrate_release" | "skip";
