// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlannedCopy } from "./PlannedCopy";
import type { PlannedDeletion } from "./PlannedDeletion";
import type { Skipped } from "./Skipped";

/**
 * Everything a run would do.
 */
export type Plan = { 
/**
 * Files to write, in walk order.
 */
copies: Array<PlannedCopy>, 
/**
 * Files to remove. Always empty unless the layout deletes.
 */
deletions: Array<PlannedDeletion>, 
/**
 * Directories to create, so a source folder that happens to be empty
 * still appears in the backup.
 */
directories: Array<string>, 
/**
 * Entries left out, each with a reason.
 */
skipped: Array<Skipped>, 
/**
 * Total bytes across [`Self::copies`].
 */
bytes: number, 
/**
 * How many files were already at the destination when the plan was
 * made. Zero for a snapshot, which compares against nothing.
 *
 * Carried so that a deletion can be weighed against what is there: ten
 * files going from a backup of twelve is a different event from ten
 * going from a backup of ten thousand, and only the first is worth
 * stopping an unattended run over.
 */
destination_files: number, };
