// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file the run would remove from the destination.
 */
export type PlannedDeletion = { 
/**
 * Path relative to the destination root.
 */
relative: string, 
/**
 * Size in bytes, so a preview can say how much would go.
 */
bytes: number, };
