// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Plan } from "./Plan";

/**
 * What a run would do at one of a rule's destinations.
 */
export type PlanOutcome = { "kind": "ready", 
/**
 * What the run would do.
 */
plan: Plan, } | { "kind": "unavailable", 
/**
 * Wording fit to show the user.
 */
reason: string, };
