// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopyReason } from "./CopyReason";

/**
 * One file the run would write.
 */
export type PlannedCopy = { 
/**
 * Path relative to the source root. Absolute paths are rebuilt by the
 * copier from the roots it was given, never carried across the IPC
 * boundary (`docs/PLAN.md` §4, T1).
 */
relative: string, 
/**
 * Size in bytes, for progress and for the space check.
 */
bytes: number, 
/**
 * Why it is in the plan.
 */
reason: CopyReason, };
