// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a pruning pass did.
 */
export type PruneReport = { 
/**
 * Snapshot folders removed.
 */
pruned: number, 
/**
 * Folders that could not be removed, with the reason. The run is not
 * failed over one — the backup itself is already written — but it is
 * not silent either.
 */
failures: Array<string>, };
