// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many snapshots to keep.
 *
 * Snapshots accumulate until the drive is full, so retention is part of that
 * layout rather than an optional extra (`docs/PLAN.md` §1.1c). Pruning happens
 * only after a run succeeds.
 */
export type Retention = { "kind": "unlimited" } | { "kind": "keep_last_n", "value": number } | { "kind": "keep_days", "value": number };
