// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DestinationStatus } from "./DestinationStatus";
import type { Due } from "./Due";
import type { Rule } from "./Rule";
import type { Run } from "./Run";
import type { Tag } from "./Tag";
import type { VolumeStatus } from "./VolumeStatus";

/**
 * One row of the rule table.
 */
export type RuleRow = { 
/**
 * The rule.
 */
rule: Rule, 
/**
 * Its tags, for the first column and for filtering.
 */
tags: Array<Tag>, 
/**
 * Where it writes, and whether those places are reachable.
 */
destinations: Array<DestinationStatus>, 
/**
 * The source volume's status. A rule whose *source* is missing cannot
 * run either, which the mock-up does not account for.
 */
source: VolumeStatus, 
/**
 * The most recent run, or `None` if it has never run. The table shows
 * "Never run" for `None`, which is distinct from a failure.
 */
last_run: Run | null, 
/**
 * When it will next start by itself.
 *
 * Answered here rather than in the frontend because the answer is
 * calendar arithmetic in the machine's own time zone, and duplicating
 * that in TypeScript would mean two implementations that could
 * disagree about what day it is.
 */
due: Due, };
