// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Layout } from "./Layout";
import type { Packaging } from "./Packaging";
import type { PlaceholderPolicy } from "./PlaceholderPolicy";
import type { Retention } from "./Retention";
import type { Schedule } from "./Schedule";
import type { VolumePath } from "./VolumePath";

/**
 * Everything about a rule except its identity.
 *
 * Separated from [`Rule`] so that creating and updating take the same type,
 * with no placeholder id and no duplicated field list.
 */
export type RuleSpec = { 
/**
 * Display name.
 */
name: string, 
/**
 * Whether the scheduler considers this rule at all.
 */
enabled: boolean, 
/**
 * What is being backed up.
 */
source: VolumePath, 
/**
 * How the backup is laid out.
 */
layout: Layout, 
/**
 * Whether files are archived.
 */
packaging: Packaging, 
/**
 * Whether mirror mode may remove files absent from the source.
 *
 * Off by default, and the one setting that can destroy data
 * (`docs/PLAN.md` §4, T4).
 */
allow_deletions: boolean, 
/**
 * How many snapshots to keep.
 */
retention: Retention, 
/**
 * How often to run.
 */
schedule: Schedule, 
/**
 * Run when a destination volume is attached.
 */
run_on_connect: boolean, 
/**
 * Make up runs missed while the machine was off or the drive absent.
 */
catch_up: boolean, 
/**
 * What to do about cloud placeholders.
 */
placeholders: PlaceholderPolicy, 
/**
 * Cap on bytes hydrated in one run. `None` means no cap.
 */
hydrate_budget_bytes: number | null, 
/**
 * Whether to follow symlinks and junctions.
 *
 * Off by default: following them lets a link inside the source tree
 * redirect the copy outside it (`docs/PLAN.md` §4, T2).
 */
follow_symlinks: boolean, 
/**
 * Glob patterns excluded from the backup.
 */
excludes: Array<string>, };
