// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a rule was refused.
 *
 * Carries enough detail for the UI to point at the field that caused it,
 * rather than showing one opaque "invalid rule" message.
 */
export type RuleProblem = { "kind": "empty_name" } | { "kind": "source_is_destination", 
/**
 * Which destination, by position in the list.
 */
destination_index: number, } | { "kind": "destination_inside_source", 
/**
 * Which destination, by position in the list.
 */
destination_index: number, } | { "kind": "source_inside_destination", 
/**
 * Which destination, by position in the list.
 */
destination_index: number, } | { "kind": "duplicate_destination", 
/**
 * The later of the two, by position in the list.
 */
destination_index: number, } | { "kind": "destination_is_volume_root", 
/**
 * Which destination, by position in the list.
 */
destination_index: number, } | { "kind": "destination_is_system_path", 
/**
 * Which destination, by position in the list.
 */
destination_index: number, 
/**
 * The path that matched, for the message.
 */
path: string, } | { "kind": "no_destinations" } | { "kind": "source_volume_unusable", 
/**
 * Why, in the same words the table uses.
 */
reason: string, } | { "kind": "destination_volume_unusable", 
/**
 * Which destination, by position in the list.
 */
destination_index: number, 
/**
 * Why, in the same words the table uses.
 */
reason: string, } | { "kind": "path_escapes_volume", 
/**
 * The offending path.
 */
path: string, };
