// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DestinationId } from "./DestinationId";
import type { RuleId } from "./RuleId";
import type { RunId } from "./RunId";
import type { RunResult } from "./RunResult";
import type { RunStats } from "./RunStats";
import type { RunTrigger } from "./RunTrigger";

/**
 * One execution of a rule against one destination.
 */
export type Run = { 
/**
 * Row id.
 */
id: RunId, 
/**
 * The rule that ran.
 */
rule: RuleId, 
/**
 * The destination written to.
 */
destination: DestinationId, 
/**
 * What started it.
 */
trigger: RunTrigger, 
/**
 * Start time, as a Unix timestamp.
 */
started_at: number, 
/**
 * Finish time, or `None` while the run is in progress.
 */
finished_at: number | null, 
/**
 * Outcome, or `None` while in progress.
 */
result: RunResult | null, 
/**
 * What the run did.
 */
stats: RunStats, 
/**
 * Failure message, where the run failed.
 */
error: string | null, 
/**
 * The snapshot folder written, for `Layout::Snapshot`.
 */
snapshot_path: string | null, };
