// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventLevel } from "./EventLevel";
import type { RunId } from "./RunId";

/**
 * A per-file problem recorded during a run.
 */
export type RunEvent = { 
/**
 * The run this belongs to.
 */
run: RunId, 
/**
 * How serious it was.
 */
level: EventLevel, 
/**
 * The file concerned.
 */
path: string, 
/**
 * What happened.
 */
message: string, };
