// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleId } from "./RuleId";
import type { RunSummary } from "./RunSummary";

/**
 * What the window is told when a run stops.
 */
export type RunFinished = { 
/**
 * The rule that ran.
 */
rule: RuleId, 
/**
 * One entry per destination, in the rule's order.
 */
summaries: Array<RunSummary>, 
/**
 * Why the run could not be attempted at all. The summaries are empty
 * when this is set.
 */
error: string | null, };
