// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleId } from "../../../src/types/RuleId";

/**
 * What the window is told while a run is going.
 */
export type RunProgress = { 
/**
 * The rule being run.
 */
rule: RuleId, 
/**
 * The file being copied, relative to the source root. Shown, not used
 * to resolve anything.
 */
file: string, 
/**
 * Files finished so far.
 */
files_done: number, 
/**
 * Files the plan holds in total, across the destinations planned so
 * far.
 */
files_total: number, 
/**
 * Bytes written so far.
 */
bytes_done: number, 
/**
 * Bytes the plan holds in total.
 */
bytes_total: number, };
