// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counters describing what a run did.
 */
export type RunStats = { 
/**
 * Files written to the destination.
 */
files_copied: number, 
/**
 * Files that could not be read or written, and were left out.
 */
files_skipped: number, 
/**
 * Files removed from the destination.
 */
files_deleted: number, 
/**
 * Bytes written.
 */
bytes_copied: number, 
/**
 * Bytes the archive occupies, where packaging applied. Reported so the
 * compression setting can be judged on evidence (`docs/PLAN.md` §1.1b).
 */
compressed_bytes: number | null, 
/**
 * Cloud placeholders downloaded.
 */
placeholders_hydrated: number, 
/**
 * Cloud placeholders left alone.
 */
placeholders_skipped: number, 
/**
 * Bytes downloaded from the cloud.
 */
bytes_hydrated: number, 
/**
 * Bytes released back to the cloud after copying.
 */
bytes_released: number, };
