// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DestinationId } from "./DestinationId";
import type { RunId } from "./RunId";
import type { RunResult } from "./RunResult";
import type { RunStats } from "./RunStats";

/**
 * What one destination's run did, as the history records it.
 */
export type RunSummary = { 
/**
 * Which destination was written to.
 */
destination: DestinationId, 
/**
 * The history row, or `None` where the destination was skipped before
 * a run was ever started.
 */
run: RunId | null, 
/**
 * How it finished. `None` means it never started.
 */
result: RunResult | null, 
/**
 * What it did.
 */
stats: RunStats, 
/**
 * Why it did not start, in words fit to show someone.
 */
skipped: string | null, };
