// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What caused a run to start.
 */
export type RunTrigger = "manual" | "schedule" | "catch_up" | "on_connect";
