// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How often a rule wants to run.
 *
 * This is an upper bound on frequency, not a promise: a rule whose destination
 * is unplugged runs when the drive next appears (`docs/PLAN.md` §1.1d).
 */
export type Schedule = { "kind": "manual" } | { "kind": "daily" } | { "kind": "weekly" } | { "kind": "monthly" } | { "kind": "cron", "value": string };
