// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkipReason } from "./SkipReason";

/**
 * One entry the run would pass over.
 */
export type Skipped = { 
/**
 * Path relative to the source root.
 */
relative: string, 
/**
 * Why it was left out.
 */
reason: SkipReason, 
/**
 * What went wrong, where there is more to say than the reason.
 */
detail: string | null, };
