// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an entry was left out of the plan.
 *
 * These are not errors — the run continues — but each one means a file the
 * user might have expected to be backed up will not be, so every one is
 * named rather than silently dropped.
 */
export type SkipReason = "excluded" | "symlink" | "escapes_source" | "too_deep" | "unreadable";
