// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Free and total bytes on a volume.
 */
export type SpaceInfo = { 
/**
 * Bytes currently available to this user.
 */
available: number, 
/**
 * Total capacity.
 */
total: number, };
