// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriveType } from "./DriveType";
import type { VolumeId } from "./VolumeId";
import type { VolumeIdentity } from "./VolumeIdentity";

/**
 * A volume as recorded in the database.
 */
export type StoredVolume = { 
/**
 * Row id.
 */
id: VolumeId, 
/**
 * Stable identity, as produced by the platform layer.
 */
identity: VolumeIdentity, 
/**
 * Volume serial, where the platform exposes one.
 */
serial: string | null, 
/**
 * Human-readable label.
 */
label: string | null, 
/**
 * Filesystem name.
 */
filesystem: string | null, 
/**
 * What backs the volume, as last seen.
 */
drive_type: DriveType, 
/**
 * Whether this volume is, or contains, a cloud sync root.
 */
is_sync_root: boolean, 
/**
 * When the volume was last seen attached, as a Unix timestamp.
 */
last_seen_at: number | null, 
/**
 * Where it was last mounted. Display only.
 */
last_mount: string | null, };
