// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagId } from "./TagId";

/**
 * A colour-coded tag.
 */
export type Tag = { 
/**
 * Row id.
 */
id: TagId, 
/**
 * Display name.
 */
name: string, 
/**
 * Palette token, not a raw colour: the UI resolves it against the
 * contrast-checked theme so a tag cannot be made unreadable.
 */
colour: string, };
