// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrashFailure } from "./TrashFailure";

/**
 * What a deletion pass actually did.
 */
export type TrashReport = { 
/**
 * Files moved into the trash folder.
 */
files_trashed: number, 
/**
 * Bytes they occupied.
 */
bytes_trashed: number, 
/**
 * The folder they went to, where anything moved. Reported so the run
 * history can tell someone exactly where to look.
 */
folder: string | null, 
/**
 * Files that could not be moved. Each one is still where it was.
 */
failures: Array<TrashFailure>, 
/**
 * Whether the pass stopped because it was asked to.
 */
cancelled: boolean, };
