// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file that could not be moved out of the way.
 */
export type TrashFailure = { 
/**
 * Path relative to the destination root.
 */
relative: string, 
/**
 * What went wrong, in the words the OS used.
 */
message: string, };
