// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Availability } from "./Availability";
import type { StoredVolume } from "./StoredVolume";

/**
 * A volume and whether it can be used right now.
 */
export type VolumeStatus = { 
/**
 * What the database knows about this volume.
 */
volume: StoredVolume, 
/**
 * Whether it can be written to, and if not, why.
 */
availability: Availability, 
/**
 * Where it is mounted right now, if it is attached.
 */
mount_point: string | null, };
