// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaseSensitivity } from "./CaseSensitivity";
import type { DriveType } from "./DriveType";
import type { VolumeIdentity } from "./VolumeIdentity";

/**
 * A volume as the platform currently sees it.
 */
export type VolumeInfo = { 
/**
 * Stable identity, used to recognise this volume on reconnection.
 */
identity: VolumeIdentity, 
/**
 * Where the volume is mounted right now. Display and resolution only;
 * never persisted as the thing that identifies the volume.
 */
mount_point: string, 
/**
 * Volume serial, where the platform exposes one. Changes on reformat, so
 * it corroborates `identity` rather than replacing it.
 */
serial: string | null, 
/**
 * Human-readable label, for the UI.
 */
label: string | null, 
/**
 * Filesystem name, e.g. `NTFS`, `exFAT`, `ext4`. Drives the mtime
 * tolerance: FAT32 stores timestamps to two seconds (`docs/PLAN.md` §1.1f).
 */
filesystem: string | null, 
/**
 * What backs the volume.
 */
drive_type: DriveType, 
/**
 * How this filesystem compares names.
 */
case_sensitivity: CaseSensitivity, 
/**
 * Whether this volume is, or contains, a cloud sync root. Shelv treats
 * such paths as read-only sources.
 */
is_sync_root: boolean, };
