// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VolumeIdentityKind } from "./VolumeIdentityKind";

/**
 * A stable, platform-specific volume identity.
 */
export type VolumeIdentity = { 
/**
 * Which scheme `value` is written in.
 */
kind: VolumeIdentityKind, 
/**
 * The opaque identity itself.
 */
value: string, };
