// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VolumeId } from "./VolumeId";

/**
 * A location expressed as a volume plus a path relative to its mount point.
 *
 * Never an absolute path: the mount point moves between sessions, the volume
 * identity does not (`docs/PLAN.md` §1.1a).
 */
export type VolumePath = { 
/**
 * The volume this path lives on.
 */
volume: VolumeId, 
/**
 * Path relative to the volume's mount point.
 */
relative: string, };
