// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a volume is identified across reconnections.
 *
 * Drive letters and mount points are **not** identities: Windows reassigns
 * letters from a registry mapping, so a rule keyed on `E:` can end up writing
 * to a different disk (`docs/PLAN.md` §1.1a). The value is opaque to the
 * engine and to the database; only the platform layer interprets it.
 */
export type VolumeIdentityKind = "windows_volume_guid" | "linux_fs_uuid";
