#!/usr/bin/env bash
# Regenerates src/types/ from the Rust types, then writes the barrel file.
#
# Run after changing anything that crosses the IPC boundary:
#   ./scripts/gen-types.sh
set -euo pipefail
cd "$(dirname "$0")/.."

TYPES_DIR="src/types"

# Stale files are not overwritten by ts-rs, only added to, so a renamed or
# deleted Rust type would leave its .ts behind forever.
rm -rf "$TYPES_DIR"
cargo test --package shelv-core --quiet export_bindings >/dev/null

if [ ! -d "$TYPES_DIR" ]; then
    echo "no types were generated — is the export_bindings test still present?" >&2
    exit 1
fi

# A barrel, so the frontend imports from one place and an unused generated
# type shows up as a lint rather than going unnoticed.
{
    echo "// Generated by scripts/gen-types.sh. Do not edit."
    echo "//"
    echo "// These mirror the Rust types in shelv-core that cross the IPC"
    echo "// boundary. CI fails if they drift from the Rust."
    echo
    for f in "$TYPES_DIR"/*.ts; do
        name="$(basename "$f" .ts)"
        [ "$name" = "index" ] && continue
        echo "export type { $name } from \"./$name\";"
    done
} > "$TYPES_DIR/index.ts"

echo "generated $(find "$TYPES_DIR" -name '*.ts' | wc -l) type files"
